services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: antonini-app
        container_name: antonini-app
        volumes:
            - .:/var/www
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
        networks:
            - antonini-network

    web:
        image: nginx:alpine
        container_name: antonini-web
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
            # EL NGINX CONF PARA EL ERROR 413
            - ./nginx-custom.conf:/etc/nginx/conf.d/custom.conf 
        networks:
            - antonini-network
    # ... resto igual (db, networks)

    db:
        image: mysql:8.0
        container_name: antonini-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: antonini_beta
            MYSQL_ROOT_PASSWORD: secret_password
        ports:
            - "3307:3306"
        networks:
            - antonini-network

networks:
    antonini-network:
        driver: bridge
