<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CurrentAccount extends Model
{
    use HasFactory;

    protected $fillable = [
        'customer_id',
        'invoice_id',
        'reservation_id',
        'reservation_payment_id',
        'service_order_id',
        'concept',
        'debit',
        'credit',
        'balance',
        'payment_date',
        'status',
        'notes',
    ];

    protected $casts = [
        'debit'        => 'float',
        'credit'       => 'float',
        'balance'      => 'float',
        'payment_date' => 'date',
    ];

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function invoice()
    {
        return $this->belongsTo(Invoice::class);
    }

    public function reservation()
    {
        return $this->belongsTo(Reservation::class);
    }

    public function reservationPayment()
    {
        return $this->belongsTo(\App\Models\ReservationPayment::class);
    }

    public function serviceOrder()
    {
        return $this->belongsTo(ServiceOrder::class);
    }

    public function isAutoGenerated(): bool
    {
        return $this->reservation_id || $this->reservation_payment_id || $this->service_order_id || $this->invoice_id;
    }
}
